/*
 * plugin-host.h - C interface to the tmux plugin host (Rust staticlib).
 *
 * GENERATED by cbindgen from plugin-host/host; do not edit by hand.
 * Regenerate from plugin-host/host with:
 *     cbindgen --crate plugin-host --output ../include/plugin-host.h
 *
 * Threading contract:
 *  - All pgh_* functions are main-thread only.
 *  - Vtable callbacks are invoked only synchronously from inside pgh_* calls.
 *  - Vtable callbacks may re-enter pgh_notify, pgh_async_complete and
 *    pgh_mode_event (all enqueue-only), nothing else.
 */

#ifndef PLUGIN_HOST_H
#define PLUGIN_HOST_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Bodies above this many bytes are compressed (level 3). Base64 on the
 * wire costs a third; compression pays it back on anything that matters.
 */
#define COMPRESS_ABOVE 4096

#define READ_STATE (1 << 0)

#define WRITE_OPTIONS (1 << 1)

#define SEND_KEYS (1 << 2)

#define CAPTURE_PANE (1 << 3)

#define DISPLAY_MESSAGE (1 << 4)

#define TIMERS (1 << 5)

#define RUN_PROCESS (1 << 6)

#define RUN_COMMAND (1 << 7)

#define CROSS_SCOPE (1 << 8)

#define POPUP (1 << 9)

#define MENU (1 << 10)

#define FS_READ (1 << 11)

#define FS_WRITE (1 << 12)

#define MODE (1 << 13)

#define FS_LIST (1 << 14)

/**
 * Lets fs_read and fs_list leave the sandbox: an absolute path means
 * what it says, and `..` may walk out. Relative paths still resolve
 * against the plugin's data directory, exactly as a process resolves
 * against its cwd. This grants no power a plugin with `run-process`
 * does not already have; it exists so a plugin can read a directory
 * WITHOUT reaching for a shell.
 */
#define FS_READ_ANY (1 << 15)

/**
 * The same escape for fs_write. Strictly the more dangerous half, so it
 * is a separate grant.
 */
#define FS_WRITE_ANY (1 << 16)

/**
 * The plugin's own SQLite database (`db_*` imports): one file,
 * `store.db`, inside its data directory. A future `db-read` (read-only
 * access to other plugins' databases, named in a `[caps.db] read = [...]`
 * sidecar list that mirrors `argv0`) would be its own bit.
 */
#define DB (1 << 17)

/**
 * Read environment variables from a pane's foreground process
 * (`pane_env`). Restricted to the names on the `[caps.env-read] names`
 * allowlist, because a process environment routinely holds secrets.
 */
#define ENV_READ (1 << 18)

/**
 * The escape hatch: read ANY variable, ignoring the allowlist. A
 * separate grant, like `fs-read-any`.
 */
#define ENV_READ_ANY (1 << 19)

/**
 * Read the open-file paths of a pane's foreground process
 * (`pane_fds`). Reveals which files a process holds open, so it is its
 * own grant, separate from `env-read`.
 */
#define PANE_FDS (1 << 20)

/**
 * Call services other plugins register (`service_call`,
 * `service_subscribe`), on this server or a linked one. The
 * `[caps.services] call = ["agents@*"]` sidecar list narrows the targets.
 */
#define SERVICE_CALL (1 << 21)

/**
 * Register service methods and emit topics (`service_register`,
 * `service_reply`, `service_emit`).
 */
#define SERVICE_SERVE (1 << 22)

/**
 * Deliver a message into a running Claude Code session over its inbox
 * socket (`claude_notify`). A queued user turn, not keystrokes. Never in
 * the default grants for a pushed plugin: a remote must not be able to
 * speak into this user's sessions.
 */
#define CLAUDE_NOTIFY (1 << 23)

/**
 * Granted to every plugin without being asked for.
 */
#define DEFAULT_CAPS ((READ_STATE | DISPLAY_MESSAGE) | TIMERS)

/**
 * Epoch tick granularity.
 */
#define TICK_MS 1

/**
 * Soft budget per guest callback (warn once), in ticks.
 */
#define SOFT_TICKS 2

/**
 * Hard budget per guest callback (trap), in ticks.
 *
 * Two seconds, not a few milliseconds. The cap does not police ordinary
 * work: a correct callback finishes well inside the soft budget, and a
 * legitimate burst - ranking ten thousand directory entries, say - must
 * never die for taking 20 ms. The cap catches a runaway, and it exists
 * only because a running callback blocks input, so the user cannot
 * interrupt it the way C-g interrupts Elisp. Emacs, Vim and Neovim run
 * plugin code on the UI thread with no budget at all. This is the same
 * choice, with a backstop.
 */
#define HARD_TICKS 2000

/**
 * Log levels for `pgh_host_vtable.log`.
 */
#define PGH_LOG_DEBUG 0

#define PGH_LOG_INFO 1

#define PGH_LOG_WARN 2

#define PGH_LOG_ERROR 3

/**
 * Object kinds for handle resolution and `pgh_object_destroyed`.
 */
#define PGH_OBJ_SESSION 0

#define PGH_OBJ_WINDOW 1

#define PGH_OBJ_PANE 2

#define PGH_OBJ_CLIENT 3

/**
 * Error codes for the `err` parameter of `pgh_async_complete` (the wire
 * numbers of tmux-plugin-abi's ErrorCode; 0 = success).
 */
#define PGH_ERR_BAD_REQUEST 1

#define PGH_ERR_NO_SUCH_OBJECT 4

#define PGH_ERR_LIMIT 6

#define PGH_ERR_HOST 7

#define PGH_ERR_CANCELLED 8

#define PGH_ERR_UNREACHABLE 10

#define PGH_ERR_TIMEOUT 11

/**
 * Bridge peer ids with this bit set are remote links this server made
 * (`remote-attach`); the rest are control clients of this server that
 * speak the bridge. The C side picks the transport by this bit.
 */
#define PGH_PEER_LINK (1 << 31)

/**
 * Relation queries for `pgh_host_vtable.obj_relation` (scope checks).
 */
#define PGH_REL_PANE_WINDOW 0

#define PGH_REL_SESSION_CURWIN 1

#define PGH_REL_WINDOW_IN_SESSION 2

#define PGH_REL_PANE_IN_WINDOW 3

#define PGH_REL_PANE_IN_SESSION 4

/**
 * `flags` wire values for [`do_rename`], renumbered so the wire form
 * does not depend on libc. `RENAME_EXCHANGE` swaps two existing names
 * atomically; plain replace is already atomic and is the right tool for
 * the publish-a-temp-file pattern.
 */
#define RENAME_REPLACE 0

#define RENAME_NOREPLACE 1

#define RENAME_EXCHANGE 2

/**
 * `flags` bits for [`do_list`].
 */
#define LIST_MTIME (1 << 0)

#define LIST_DIRS_ONLY (1 << 1)

/**
 * Failures within [`FAILURE_WINDOW`] before a plugin is disabled until an
 * explicit reload. A window rather than a consecutive count: a trapped
 * instance is restarted, and its init is a clean callback, so a plugin
 * that traps on its first event would otherwise restart forever without
 * ever reaching the limit.
 */
#define MAX_FAILURES 3

/**
 * zstd level for ZSTD_REF parameters. Level 3 is the library default:
 * several hundred MB/s and about a fifth of the size on terminal text.
 */
#define ZSTD_LEVEL 3

/**
 * Statement wall-clock caps, enforced by the progress handler.
 */
#define ASYNC_STATEMENT_MS 30000

#define SYNC_STATEMENT_MS 500

/**
 * Sink used wherever bytes cross the FFI from callee to caller: the
 * callee invokes the sink zero or more times with a byte run (not
 * NUL-terminated); ownership never crosses the boundary.
 */
typedef void (*pgh_sink)(void *ctx, const char *ptr, uintptr_t len);

/**
 * Host callbacks provided by tmux at `pgh_init` time.
 *
 * The struct is copied by value; tmux may discard its copy after `pgh_init`
 * returns. All function pointers must stay valid for the process lifetime.
 */
typedef struct {
  /**
   * Log a message attributed to a plugin ("host" for subsystem messages).
   */
  void (*log)(int level, const char *plugin, const char *msg);
  /**
   * Emit the binary object-list buffer (u32 count + records, see
   * abi-types) for all live objects of `kind` (PGH_OBJ_*) into the sink.
   */
  void (*list_objects)(int kind, pgh_sink sink, void *ctx);
  /**
   * Emit one binary object record describing the live object (kind, id)
   * into the sink and return 0; return -1 without emitting if it no
   * longer exists. This is the weak-handle validity check.
   */
  int (*resolve_object)(int kind, uint32_t id, pgh_sink sink, void *ctx);
  /**
   * Relation query for scope checks (PGH_REL_*): PANE_WINDOW(a=pane) ->
   * window id; SESSION_CURWIN(a=session) -> window id;
   * WINDOW_IN_SESSION(a=window, b=session), PANE_IN_WINDOW(a=pane,
   * b=window), PANE_IN_SESSION(a=pane, b=session) -> 1/0.
   * -1 = no such object.
   */
  int64_t (*obj_relation)(int rel, uint32_t a, uint32_t b);
  /**
   * Send keys to a pane; literal != 0 sends `keys` as UTF-8 characters,
   * otherwise `keys` is one tmux key name. 0 ok, -1 dead pane, -2 bad key.
   */
  int (*send_keys)(uint32_t pane_id, const char *keys, int literal);
  /**
   * Capture pane text into the sink (one line per row, trailing \n).
   * start/end rows relative to the visible top (negative = history),
   * end inclusive. 0 ok, -1 dead pane.
   */
  int (*capture_pane)(uint32_t pane_id, int start, int end, int escapes, pgh_sink sink, void *ctx);
  /**
   * Read one environment variable from a pane's foreground process as
   * a string. 0 ok, -1 dead pane, -2 no such variable.
   */
  int (*pane_env)(uint32_t pane_id, const char *name, pgh_sink sink, void *ctx);
  /**
   * Emit the open-file paths of a pane's foreground process, one per
   * line. 0 ok, -1 dead pane, -2 none.
   */
  int (*pane_fds)(uint32_t pane_id, pgh_sink sink, void *ctx);
  /**
   * Grep the grids of `n_ids` panes for `pattern`. Emits one match
   * record per matching pane through the sink; returns the match count
   * (>=0) or -1 on error.
   */
  int (*panes_search)(const uint32_t *ids,
                      uint32_t n_ids,
                      const char *pattern,
                      uint32_t flags,
                      uint32_t max_lines,
                      pgh_sink sink,
                      void *ctx);
  /**
   * The pid of a pane's foreground process group, or -1 if dead.
   */
  int (*pane_pid)(uint32_t pane_id);
  /**
   * Get an option value as a string (kind -1 = server/global scope).
   * 0 ok, -1 dead target, -2 no such option.
   */
  int (*get_option)(int kind, uint32_t id, const char *name, pgh_sink sink, void *ctx);
  /**
   * Set a user (@-prefixed) option. 0 ok, -1 dead target, -2 not @-option.
   */
  int (*set_option)(int kind, uint32_t id, const char *name, const char *value);
  /**
   * Status-line message (client_id, or -1 for all attached clients) plus
   * the server message log. 0 ok, -1 no such client.
   */
  int (*display_message)(int client_id, const char *plugin, const char *msg);
  /**
   * Start a shell command as a job; completion arrives later via
   * pgh_async_complete(token, 0, status, signalled, output, len).
   * 0 started, -1 failed to start.
   */
  int (*run_job)(const char *cmd, const char *cwd, uint64_t token);
  /**
   * Queue a tmux command string on the command queue (NOHOOKS); the
   * completion callback delivers pgh_async_complete(token, ...) after it
   * runs (parse errors arrive as error completions). -1 internal failure.
   */
  int (*run_command)(const char *cmd, uint64_t token);
  /**
   * One-shot timer; fires pgh_async_complete(token, 0, 0, 0, NULL, 0).
   * Returns a timer id usable with timer_cancel.
   */
  uint64_t (*timer_start)(uint64_t ms, uint64_t token);
  /**
   * Cancel a pending timer (no completion is delivered). 0 ok, -1 unknown.
   */
  int (*timer_cancel)(uint64_t timer_id);
  /**
   * A plugin changed state in a way the user should see (disabled,
   * load failed, ...). The C side surfaces it on status lines and in
   * the server message log.
   */
  void (*plugin_state_changed)(const char *plugin, const char *state, const char *reason);
  /**
   * Open a plugin UI mode in a freshly spawned empty floating pane in
   * `window`. x/y are top-left cell offsets, -1 = centered; `title` may
   * be NULL. Returns the new mode id (> 0) synchronously, or a negative
   * error: -1 no such window, -2 spawn failed, -3 mode init failed.
   * Events for the mode arrive later via pgh_mode_event.
   */
  int64_t (*mode_open)(uint32_t window,
                       uint32_t width,
                       uint32_t height,
                       int x,
                       int y,
                       const char *title);
  /**
   * Parse ANSI bytes into a mode's screen (server-side escape parser,
   * no tty round-trip). 0 ok, -1 no such mode.
   */
  int (*mode_write)(uint64_t mode, const uint8_t *data, uintptr_t len);
  /**
   * Set (pane >= 0) or clear (pane < 0) a mode's retained preview rect:
   * a live blit of the source pane's grid at (x, y), size (w, h),
   * refreshed periodically until cleared. 0 ok, -1 no such mode,
   * -2 rect does not fit the mode screen.
   */
  int (*mode_preview)(uint64_t mode, int64_t pane, uint32_t x, uint32_t y, uint32_t w, uint32_t h);
  /**
   * Close a mode: the floating pane is torn down at the next safe
   * point (never synchronously inside this call), which delivers
   * pgh_mode_event(mode, "mode-closed", ...). 0 ok, -1 no such mode.
   */
  int (*mode_close)(uint64_t mode);
  /**
   * Move a mode's floating pane to another window, keeping the pane,
   * the mode and its screen contents intact (join-pane style relink;
   * at most a mode-resize event follows). x/y as for mode_open
   * (-1 = centered). 0 ok, -1 no such mode, -2 no such window or
   * unmovable pane, -3 the move would empty the source window.
   */
  int (*mode_move)(uint64_t mode, uint32_t window, int x, int y);
  /**
   * Resize a mode's floating pane. Width and height are content cells,
   * as in mode_open; the border sits outside them. Clamped to the
   * window, top-left corner kept, so a growing panel expands down and
   * right. A mode-resize event follows with the size actually given.
   * 0 ok, -1 no such mode or the pane is not floating, -2 window too
   * small.
   */
  int (*mode_resize)(uint64_t mode, uint32_t width, uint32_t height);
  /**
   * Expand a format string against a scope (kind -1 = server/global,
   * else PGH_OBJ_SESSION/WINDOW/PANE) into the sink. Jobs (#()) are
   * disabled. 0 ok, -1 dead/bad target.
   */
  int (*format_expand)(int kind, uint32_t id, const char *fmt, pgh_sink sink, void *ctx);
  /**
   * Send an opaque bridge frame to a peer (PGH_PEER_LINK bit: a remote
   * link, sent as a `plugin-bridge` control mode command; else a
   * control client, sent as a `%bridge` line). The bytes are copied
   * before this returns. 0 ok, -1 no such peer or peer down.
   */
  int (*bridge_send)(uint32_t peer, const uint8_t *data, uintptr_t len);
} pgh_host_vtable;

/**
 * Completion callback of `pgh_plugin_update`: called exactly once, later,
 * from a drain, with the report (`rc` 0) or an error message (`rc` -1).
 * `text` is NUL-terminated as well as `len` bytes long.
 */
typedef void (*pgh_done)(void *ctx, int rc, const char *text, uintptr_t len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the plugin host. Must be called once, from the tmux server
 * main thread, before any other pgh_* function. Returns 0 on success.
 *
 * # Safety
 * `vt` must point to a fully-populated vtable; the function pointers must
 * stay valid for the life of the process.
 */
int pgh_init(const pgh_host_vtable *vt);

/**
 * Shut down the plugin host: unload all plugins and stop the epoch ticker
 * thread. Called once from the server exit path; pgh_* calls after this are
 * no-ops. Safe to call even if pgh_init failed.
 */
void pgh_shutdown(void);

/**
 * Load (or replace) a plugin. `scope` may be NULL (defaults to server);
 * `role` may be NULL (defaults to both) or "both", "view" or "provider";
 * `caps` is an array of `ncaps` capability names; `opts` is an array of
 * `nopts` config entries ("key=value", or a bare "key" meaning true).
 * Compiles and validates the module synchronously (obvious errors are
 * written to `err_sink` and -1 returned); instantiation and guest init are
 * queued for the next drain. The C side should call
 * plugin_schedule_drain() after a successful return.
 *
 * # Safety
 * All strings must be NUL-terminated; the arrays must hold the declared
 * counts; `err_sink` must be valid.
 */
int pgh_plugin_load(const char *name,
                    const char *path,
                    const char *scope,
                    const char *role,
                    const char *const *caps,
                    uintptr_t ncaps,
                    const char *const *opts,
                    uintptr_t nopts,
                    pgh_sink err_sink,
                    void *err_ctx);

/**
 * Reconcile the managed plugin pool against the TOML manifest at
 * `manifest_path` (see WRITING-PLUGINS.md): load new entries, upsert
 * changed ones, unload managed plugins the manifest no longer names. A
 * manifest that fails to parse or validate changes nothing and returns
 * -1 with the error in the sink; on success the sink receives a summary
 * line (plus any per-entry apply failures) and 0 is returned. The C side
 * should call plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `manifest_path` must be NUL-terminated; `err_sink` must be valid.
 * `update-plugins [-n] manifest`: resolve the manifest's registry again,
 * report what changes against the lock and, unless `check_only`, write
 * the new lock and sync. `done` is called exactly once from a later
 * drain with the report; it is never called before this returns. When
 * the manifest is unusable (or the work fails before anything is
 * queued), the error goes to `err_sink`, -1 is returned and `done` is
 * never called.
 *
 * # Safety
 * `manifest_path` NUL-terminated; `err_sink` and `done` valid function
 * pointers; `done_ctx` must stay valid until `done` runs.
 */
int pgh_plugin_update(const char *manifest_path,
                      int check_only,
                      pgh_sink err_sink,
                      void *err_ctx,
                      pgh_done done,
                      void *done_ctx);

int pgh_plugin_sync(const char *manifest_path, pgh_sink err_sink, void *err_ctx);

/**
 * Reload a plugin from disk (or all plugins when `name` is NULL): every
 * instance is swapped transactionally with snapshot/migrate and a new
 * generation; failures keep the old instance running. Errors go to the
 * sink; returns -1 if any plugin failed.
 *
 * # Safety
 * `name` NUL-terminated or NULL; `err_sink` valid.
 */
int pgh_plugin_reload(const char *name, pgh_sink err_sink, void *err_ctx);

/**
 * Enable (1) or disable (0) a plugin. Returns 0, or -1 if unknown.
 *
 * # Safety
 * `name` must be NUL-terminated.
 */
int pgh_plugin_set_enabled(const char *name, int enabled);

/**
 * Write the tail of the plugin log ring (optionally filtered by plugin
 * name; NULL = all) into the sink as preformatted lines.
 *
 * # Safety
 * `name` NUL-terminated or NULL; `sink` valid.
 */
void pgh_query_log(const char *name, uint32_t limit, pgh_sink sink, void *ctx);

/**
 * Unload a plugin by name. Returns 0, or -1 if unknown. Guest on_unload
 * runs at the next drain.
 *
 * # Safety
 * `name` must be NUL-terminated.
 */
int pgh_plugin_unload(const char *name);

/**
 * Feed one binary event buffer (header + field block, see abi-types) into
 * the plugin event queue.
 *
 * ENQUEUE ONLY: never runs plugin code, so it is legal to call from
 * anywhere on the main thread, including from inside a vtable callback
 * (the one permitted re-entry). Guest delivery happens at the next
 * pgh_drain. The C side should call plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `event` must point at `len` readable bytes (copied before returning).
 */
void pgh_notify(const uint8_t *event, uintptr_t len);

/**
 * Intern a name (event name or payload key), returning its stable id
 * (>= 1). The same table serves guests through the `intern` import, so
 * the ids the C bridge writes into event buffers are the ids guests
 * subscribe to and compare against.
 *
 * # Safety
 * `name` must be NUL-terminated.
 */
uint32_t pgh_intern(const char *name);

/**
 * Invalidate plugin state tied to a dead tmux object (kind = PGH_OBJ_*).
 *
 * MARK AND QUEUE ONLY: never runs guest code, because this is called from
 * deep teardown paths (window_destroy can run inside command-queue
 * callbacks). Instance unload work happens at the next pgh_drain.
 */
void pgh_object_destroyed(int kind, uint32_t id);

/**
 * Deliver the result of an async operation started through the vtable
 * (run_job, run_command, timer_start, ...). `err` is 0 on success or an
 * ErrorCode number; `data`/`len` carry the per-method payload (job
 * output; the error message when err != 0) and may be NULL/0.
 *
 * ENQUEUE ONLY, like pgh_notify: legal to call from any main-thread
 * context, including from inside vtable callbacks. Generation checks at
 * drain time drop completions whose instance died or was reloaded. The C
 * side should call plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `data` must point at `len` readable bytes or be NULL (copied before
 * returning).
 */
void pgh_async_complete(uint64_t token,
                        int err,
                        int64_t v0,
                        int64_t v1,
                        const uint8_t *data,
                        uintptr_t len);

/**
 * Deliver a mode event (mode-key, mode-resize, mode-closed) for a plugin
 * UI mode opened through the mode_open vtable call. `event` is a complete
 * binary event buffer built by the C side (including the mode field).
 *
 * ENQUEUE ONLY, like pgh_notify: legal to call from any main-thread
 * context, including from inside vtable callbacks. Ownership and
 * generation checks at drain time drop events whose owning instance died
 * or was reloaded. The C side should call plugin_schedule_drain()
 * afterwards.
 *
 * # Safety
 * `event` must point at `len` readable bytes (copied before returning).
 */
void pgh_mode_event(uint64_t mode_id, const uint8_t *event, uintptr_t len);

/**
 * A bridge frame arrived from a peer: a `plugin-bridge` command from a
 * control client (peer = client id) or a `%bridge` line on a remote link
 * (peer = link id | PGH_PEER_LINK). The bytes are the decoded frame.
 *
 * ENQUEUE ONLY, like pgh_notify. The C side should call
 * plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `bytes` must point at `len` readable bytes (copied before returning).
 */
void pgh_bridge_recv(uint32_t peer, const uint8_t *bytes, uintptr_t len);

/**
 * A bridge peer came up (`up` != 0, `name` = the remote host for a link
 * this server made; may be NULL) or went down. ENQUEUE ONLY. The C side
 * should call plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `name` NUL-terminated or NULL.
 */
void pgh_bridge_state(uint32_t peer, const char *name, int up);

/**
 * Run queued plugin work for at most `max_us` microseconds of wall clock
 * (0 = default budget). Returns the number of deliveries still queued;
 * when nonzero the C side re-schedules via its zero-timeout evtimer so the
 * libevent loop breathes between slices.
 *
 * ONLY to be called from the command-queue drain callback (the safe point).
 */
uint32_t pgh_drain(uint32_t max_us);

/**
 * The worker pool's pollable doorbell fd (created on first call). The
 * C side registers a persistent read event on it whose callback calls
 * pgh_fs_drain() then plugin_schedule_drain(). Returns -1 on failure.
 * The name predates the pool: it carries db completions too.
 */
int pgh_fs_notify_fd(void);

/**
 * Move finished worker completions (fs and db) onto the plugin delivery
 * queue (they are delivered to guests at the next pgh_drain). Main
 * thread only; called from the doorbell event callback.
 */
void pgh_fs_drain(void);

/**
 * Write a human-readable plugin listing (for `show-plugins`) into the sink.
 * Preformatted text, one line per plugin (plus per-instance lines when
 * `verbose` is nonzero); the C side prints lines verbatim.
 *
 * # Safety
 * `sink` must be a valid callback; `ctx` is passed through untouched.
 */
void pgh_query_plugins(int verbose, pgh_sink sink, void *ctx);

/**
 * Remember the client that ran remote-attach for a link, so the grant
 * handshake can open its menu there. `peer` is the link id | PGH_PEER_LINK.
 *
 * # Safety
 * `client` NUL-terminated or NULL.
 */
void pgh_peers_set_client(uint32_t peer, const char *client);

/**
 * `plugin-peers list`: emit the grant rows through the sink.
 *
 * # Safety
 * `sink` valid; `ctx` its context.
 */
void pgh_peers_list(pgh_sink sink, void *ctx);

/**
 * `plugin-peers allow|deny <server> [plugin]`. `state` is "allow" or
 * "deny"; `plugin` NULL means every plugin.
 *
 * # Safety
 * `server`, `state` NUL-terminated; `plugin` NUL-terminated or NULL.
 */
int pgh_peers_set(const char *server, const char *plugin, const char *state);

/**
 * `plugin-peers revoke <server> [plugin]`: delete the row. Returns 1 if a
 * row went, 0 if none, -1 on bad input.
 *
 * # Safety
 * `server` NUL-terminated; `plugin` NUL-terminated or NULL.
 */
int pgh_peers_revoke(const char *server, const char *plugin);

/**
 * `plugin-peers menu <server>`: reopen the grant menu on `client`.
 *
 * # Safety
 * `server`, `client` NUL-terminated.
 */
void pgh_peers_menu(const char *server, const char *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLUGIN_HOST_H */
