/*
 * plugin-host.h - C interface to the tmux plugin host (Rust staticlib).
 *
 * GENERATED by cbindgen from plugin-host/host; do not edit by hand.
 * Regenerate from plugin-host/host with:
 *     cbindgen --crate plugin-host --output ../include/plugin-host.h
 *
 * Threading contract:
 *  - All pgh_* functions are main-thread only.
 *  - Vtable callbacks are invoked only synchronously from inside pgh_* calls.
 *  - Vtable callbacks may re-enter pgh_notify (enqueue-only), nothing else.
 */

#ifndef PLUGIN_HOST_H
#define PLUGIN_HOST_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define READ_STATE (1 << 0)

#define WRITE_OPTIONS (1 << 1)

#define SEND_KEYS (1 << 2)

#define CAPTURE_PANE (1 << 3)

#define DISPLAY_MESSAGE (1 << 4)

#define TIMERS (1 << 5)

#define RUN_PROCESS (1 << 6)

#define RUN_COMMAND (1 << 7)

#define CROSS_SCOPE (1 << 8)

#define POPUP (1 << 9)

#define MENU (1 << 10)

#define FS_READ (1 << 11)

#define FS_WRITE (1 << 12)

/**
 * Granted to every plugin without being asked for.
 */
#define DEFAULT_CAPS ((READ_STATE | DISPLAY_MESSAGE) | TIMERS)

/**
 * Epoch tick granularity.
 */
#define TICK_MS 1

/**
 * Soft budget per guest callback (warn once), in ticks.
 */
#define SOFT_TICKS 2

/**
 * Hard budget per guest callback (trap), in ticks.
 */
#define HARD_TICKS 8

/**
 * Log levels for `pgh_host_vtable.log`.
 */
#define PGH_LOG_DEBUG 0

#define PGH_LOG_INFO 1

#define PGH_LOG_WARN 2

#define PGH_LOG_ERROR 3

/**
 * Object kinds for handle resolution and `pgh_object_destroyed`.
 */
#define PGH_OBJ_SESSION 0

#define PGH_OBJ_WINDOW 1

#define PGH_OBJ_PANE 2

#define PGH_OBJ_CLIENT 3

/**
 * Consecutive failures before a plugin is disabled until explicit reload.
 */
#define MAX_FAILURES 3

/**
 * Sink used wherever a string crosses the FFI from callee to caller: the
 * callee invokes the sink zero or more times with UTF-8 bytes (not
 * NUL-terminated); ownership never crosses the boundary.
 */
typedef void (*pgh_sink)(void *ctx, const char *ptr, uintptr_t len);

/**
 * Host callbacks provided by tmux at `pgh_init` time.
 *
 * The struct is copied by value; tmux may discard its copy after `pgh_init`
 * returns. All function pointers must stay valid for the process lifetime.
 */
typedef struct {
  /**
   * Log a message attributed to a plugin ("host" for subsystem messages).
   */
  void (*log)(int level, const char *plugin, const char *msg);
  /**
   * Emit a JSON array of all live objects of `kind` (PGH_OBJ_*) into the
   * sink. Each element carries at least {"id": n}.
   */
  void (*list_objects)(int kind, pgh_sink sink, void *ctx);
  /**
   * Emit a JSON object describing the live object (kind, id) into the
   * sink and return 0; return -1 without emitting if it no longer exists.
   * This is the weak-handle validity check.
   */
  int (*resolve_object)(int kind, uint32_t id, pgh_sink sink, void *ctx);
  /**
   * Send keys to a pane; literal != 0 sends `keys` as UTF-8 characters,
   * otherwise `keys` is one tmux key name. 0 ok, -1 dead pane, -2 bad key.
   */
  int (*send_keys)(uint32_t pane_id, const char *keys, int literal);
  /**
   * Capture pane text into the sink (one line per row, trailing \n).
   * start/end rows relative to the visible top (negative = history),
   * end inclusive. 0 ok, -1 dead pane.
   */
  int (*capture_pane)(uint32_t pane_id, int start, int end, int escapes, pgh_sink sink, void *ctx);
  /**
   * Get an option value as a string (kind -1 = server/global scope).
   * 0 ok, -1 dead target, -2 no such option.
   */
  int (*get_option)(int kind, uint32_t id, const char *name, pgh_sink sink, void *ctx);
  /**
   * Set a user (@-prefixed) option. 0 ok, -1 dead target, -2 not @-option.
   */
  int (*set_option)(int kind, uint32_t id, const char *name, const char *value);
  /**
   * Status-line message (client_id, or -1 for all attached clients) plus
   * the server message log. 0 ok, -1 no such client.
   */
  int (*display_message)(int client_id, const char *plugin, const char *msg);
  /**
   * Start a shell command as a job; completion arrives later via
   * pgh_async_complete(token, {"status","signalled","output"}, 0).
   * 0 started, -1 failed to start.
   */
  int (*run_job)(const char *cmd, const char *cwd, uint64_t token);
  /**
   * Queue a tmux command string on the command queue (NOHOOKS); the
   * completion callback delivers pgh_async_complete(token, ...) after it
   * runs (parse errors arrive as error completions). -1 internal failure.
   */
  int (*run_command)(const char *cmd, uint64_t token);
  /**
   * One-shot timer; fires pgh_async_complete(token, "{}", 0). Returns a
   * timer id usable with timer_cancel.
   */
  uint64_t (*timer_start)(uint64_t ms, uint64_t token);
  /**
   * Cancel a pending timer (no completion is delivered). 0 ok, -1 unknown.
   */
  int (*timer_cancel)(uint64_t timer_id);
  /**
   * A plugin changed state in a way the user should see (disabled,
   * load failed, ...). The C side surfaces it on status lines and in
   * the server message log.
   */
  void (*plugin_state_changed)(const char *plugin, const char *state, const char *reason);
} pgh_host_vtable;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the plugin host. Must be called once, from the tmux server
 * main thread, before any other pgh_* function. Returns 0 on success.
 *
 * # Safety
 * `vt` must point to a fully-populated vtable; the function pointers must
 * stay valid for the life of the process.
 */
int pgh_init(const pgh_host_vtable *vt);

/**
 * Shut down the plugin host: unload all plugins and stop the epoch ticker
 * thread. Called once from the server exit path; pgh_* calls after this are
 * no-ops. Safe to call even if pgh_init failed.
 */
void pgh_shutdown(void);

/**
 * Load (or replace) a plugin from a JSON LoadDescriptor. Compiles and
 * validates the module synchronously (obvious errors are written to
 * `err_sink` and -1 returned); instantiation and guest init are queued for
 * the next drain. The C side should call plugin_schedule_drain() after a
 * successful return.
 *
 * # Safety
 * `desc_json` must be NUL-terminated; `err_sink` must be valid.
 */
int pgh_plugin_load(const char *desc_json, pgh_sink err_sink, void *err_ctx);

/**
 * Reload a plugin from disk (or all plugins when `name` is NULL): every
 * instance is swapped transactionally with snapshot/migrate and a new
 * generation; failures keep the old instance running. Errors go to the
 * sink; returns -1 if any plugin failed.
 *
 * # Safety
 * `name` NUL-terminated or NULL; `err_sink` valid.
 */
int pgh_plugin_reload(const char *name, pgh_sink err_sink, void *err_ctx);

/**
 * Enable (1) or disable (0) a plugin. Returns 0, or -1 if unknown.
 *
 * # Safety
 * `name` must be NUL-terminated.
 */
int pgh_plugin_set_enabled(const char *name, int enabled);

/**
 * Write the tail of the plugin log ring (optionally filtered by plugin
 * name; NULL = all) into the sink as preformatted lines.
 *
 * # Safety
 * `name` NUL-terminated or NULL; `sink` valid.
 */
void pgh_query_log(const char *name, uint32_t limit, pgh_sink sink, void *ctx);

/**
 * Unload a plugin by name. Returns 0, or -1 if unknown. Guest on_unload
 * runs at the next drain.
 *
 * # Safety
 * `name` must be NUL-terminated.
 */
int pgh_plugin_unload(const char *name);

/**
 * Feed one event (JSON, see ABI.md) into the plugin event queue.
 *
 * ENQUEUE ONLY: never runs plugin code, so it is legal to call from
 * anywhere on the main thread, including from inside a vtable callback
 * (the one permitted re-entry). Guest delivery happens at the next
 * pgh_drain. The C side should call plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `event_json` must be a NUL-terminated string.
 */
void pgh_notify(const char *event_json);

/**
 * Invalidate plugin state tied to a dead tmux object (kind = PGH_OBJ_*).
 *
 * MARK AND QUEUE ONLY: never runs guest code, because this is called from
 * deep teardown paths (window_destroy can run inside command-queue
 * callbacks). Instance unload work happens at the next pgh_drain.
 */
void pgh_object_destroyed(int kind, uint32_t id);

/**
 * Deliver the result of an async operation started through the vtable
 * (run_job, run_command, timer_start, ...).
 *
 * ENQUEUE ONLY, like pgh_notify: legal to call from any main-thread
 * context, including from inside vtable callbacks. Generation checks at
 * drain time drop completions whose instance died or was reloaded. The C
 * side should call plugin_schedule_drain() afterwards.
 *
 * # Safety
 * `result_json` must be NUL-terminated.
 */
void pgh_async_complete(uint64_t token, const char *result_json, int is_error);

/**
 * Run queued plugin work for at most `max_us` microseconds of wall clock
 * (0 = default budget). Returns the number of deliveries still queued;
 * when nonzero the C side re-schedules via its zero-timeout evtimer so the
 * libevent loop breathes between slices.
 *
 * ONLY to be called from the command-queue drain callback (the safe point).
 */
uint32_t pgh_drain(uint32_t max_us);

/**
 * Write a human-readable plugin listing (for `show-plugins`) into the sink.
 * Preformatted text, one line per plugin (plus per-instance lines when
 * `verbose` is nonzero); the C side prints lines verbatim.
 *
 * # Safety
 * `sink` must be a valid callback; `ctx` is passed through untouched.
 */
void pgh_query_plugins(int verbose, pgh_sink sink, void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLUGIN_HOST_H */
