//! The notes tmux puts on its own prefix-table bindings (key-bindings.c),
//! so the palette can tell a stock binding from one of the user's. Generated
//! by scripts/gen-stock-notes.sh; do not edit.

pub const STOCK_NOTES: &[&str] = &[
    "Break pane to a new window",
    "Choose a paste buffer from a list",
    "Choose a session from a list",
    "Choose a window from a list",
    "Choose and detach a client from a list",
    "Clear the marked pane",
    "Create a new window",
    "Customize options",
    "Delete the most recent paste buffer",
    "Describe key binding",
    "Detach the current client",
    "Display pane menu",
    "Display pane numbers",
    "Display window information",
    "Display window menu",
    "Enter copy mode",
    "Enter copy mode and scroll up",
    "Kill current window",
    "Kill the active pane",
    "List all paste buffers",
    "List key bindings",
    "Move a floating pane",
    "Move the current window",
    "Move the visible part of the window down",
    "Move the visible part of the window left",
    "Move the visible part of the window right",
    "Move the visible part of the window up",
    "Move to the previously active pane",
    "New floating pane",
    "Paste the most recent paste buffer",
    "Prompt for a command",
    "Prompt for window index to select",
    "Redraw the current client",
    "Rename current session",
    "Rename current window",
    "Reset so the visible part of the window follows the cursor",
    "Resize the pane down",
    "Resize the pane down by 5",
    "Resize the pane left",
    "Resize the pane left by 5",
    "Resize the pane right",
    "Resize the pane right by 5",
    "Resize the pane up",
    "Resize the pane up by 5",
    "Rotate through the panes",
    "Rotate through the panes in reverse",
    "Search for a pane",
    "Select next layout",
    "Select the next pane",
    "Select the next window",
    "Select the next window with an alert",
    "Select the pane above the active pane",
    "Select the pane below the active pane",
    "Select the pane to the left of the active pane",
    "Select the pane to the right of the active pane",
    "Select the previous window",
    "Select the previous window with an alert",
    "Select the previously current window",
    "Select the tiled layout",
    "Select window 0",
    "Select window 1",
    "Select window 2",
    "Select window 3",
    "Select window 4",
    "Select window 5",
    "Select window 6",
    "Select window 7",
    "Select window 8",
    "Select window 9",
    "Send the prefix key",
    "Set the even-horizontal layout",
    "Set the even-vertical layout",
    "Set the main-horizontal layout",
    "Set the main-horizontal-mirrored layout",
    "Set the main-vertical layout",
    "Set the main-vertical-mirrored layout",
    "Show a clock",
    "Show messages",
    "Split window horizontally",
    "Split window vertically",
    "Spread panes out evenly",
    "Suspend the current client",
    "Swap the active pane with the pane above",
    "Swap the active pane with the pane below",
    "Switch to a session",
    "Switch to a window",
    "Switch to next client",
    "Switch to previous client",
    "Switch to the last client",
    "Toggle pane between floating and tiled",
    "Toggle the marked pane",
    "Zoom the active pane",
];
