//! tmux plugin host.
//!
//! Linked into the tmux server as a staticlib. Embeds Wasmtime and manages
//! plugin instances; tmux talks to it through the `pgh_*` exports declared in
//! include/plugin-host.h (generated by cbindgen; regenerate with
//! `cbindgen --crate plugin-host --output ../include/plugin-host.h` from the
//! host/ directory whenever the FFI surface changes).

mod abi;
mod caps;
mod dispatch;
mod engine;
mod events;
mod ffi;
mod hostlog;
mod registry;
mod reload;
mod state;
mod tokens;

pub use ffi::*;

use std::ffi::{c_void, CStr};
use std::os::raw::{c_char, c_int};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::OnceLock;

use registry::ScopeId;
use state::{EVENTS, REGISTRY};

static VTABLE: OnceLock<pgh_host_vtable> = OnceLock::new();

/// Set when the host crate itself has failed (an unattributable panic).
/// All pgh_* entry points become no-ops; this must never kill tmux.
static POISONED: AtomicBool = AtomicBool::new(false);

pub(crate) fn vtable() -> Option<&'static pgh_host_vtable> {
    VTABLE.get()
}

pub(crate) fn poison() {
    POISONED.store(true, Ordering::Relaxed);
    hostlog::error("host", "plugin host poisoned by internal error; plugins are disabled");
}

pub(crate) fn poisoned() -> bool {
    POISONED.load(Ordering::Relaxed)
}

/// Wrap every FFI export: catch unwinds so a host bug can never unwind into
/// C and never kills the user's tmux server.
macro_rules! ffi_guard {
    ($default:expr, $body:expr) => {{
        if crate::poisoned() {
            return $default;
        }
        match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| $body)) {
            Ok(v) => v,
            Err(_) => {
                crate::poison();
                $default
            }
        }
    }};
}
#[allow(unused_imports)] // used by other modules as they come online
pub(crate) use ffi_guard;

/// Copy a NUL-terminated C string into an owned String (lossy for any
/// non-UTF-8 bytes, which tmux names can technically contain).
pub(crate) unsafe fn cstr_lossy(ptr: *const c_char) -> Option<String> {
    if ptr.is_null() {
        return None;
    }
    Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
}

/// Push a &str through a pgh_sink.
pub(crate) unsafe fn sink_str(sink: pgh_sink, ctx: *mut c_void, s: &str) {
    sink(ctx, s.as_ptr() as *const c_char, s.len());
}

/// Initialize the plugin host. Must be called once, from the tmux server
/// main thread, before any other pgh_* function. Returns 0 on success.
///
/// # Safety
/// `vt` must point to a fully-populated vtable; the function pointers must
/// stay valid for the life of the process.
#[no_mangle]
pub unsafe extern "C" fn pgh_init(vt: *const pgh_host_vtable) -> c_int {
    ffi_guard!(-1, {
        if vt.is_null() {
            return -1;
        }
        if VTABLE.set(*vt).is_err() {
            return -1; // double init
        }
        hostlog::debug("host", "plugin host initialized");
        0
    })
}

/// Shut down the plugin host: unload all plugins and stop the epoch ticker
/// thread. Called once from the server exit path; pgh_* calls after this are
/// no-ops. Safe to call even if pgh_init failed.
#[no_mangle]
pub extern "C" fn pgh_shutdown() {
    ffi_guard!((), {
        // Give every live instance its on_unload (tiny budget) before the
        // stores drop: server shutdown is a safe point like any drain.
        let mut doomed: Vec<registry::Instance> = Vec::new();
        REGISTRY.with(|r| {
            let mut reg = r.borrow_mut();
            doomed.append(&mut reg.dying);
            let keys: Vec<usize> =
                reg.instances.iter().map(|(k, _)| k).collect();
            for key in keys {
                if let Some(inst) = reg.instances.remove(key) {
                    doomed.push(inst);
                }
            }
            reg.by_scope.clear();
        });
        for mut inst in doomed {
            let _ = inst.guest.call_on_unload();
        }
        REGISTRY.with(|r| {
            let mut reg = r.borrow_mut();
            // Stores are gone; dropping the EngineState joins the ticker.
            reg.plugins.clear();
            reg.modules.clear();
            reg.engine.take();
        });
        EVENTS.with(|e| e.borrow_mut().deliveries.clear());
        hostlog::debug("host", "plugin host shut down");
    })
}

/// Load (or replace) a plugin from a JSON LoadDescriptor. Compiles and
/// validates the module synchronously (obvious errors are written to
/// `err_sink` and -1 returned); instantiation and guest init are queued for
/// the next drain. The C side should call plugin_schedule_drain() after a
/// successful return.
///
/// # Safety
/// `desc_json` must be NUL-terminated; `err_sink` must be valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_load(
    desc_json: *const c_char,
    err_sink: pgh_sink,
    err_ctx: *mut c_void,
) -> c_int {
    ffi_guard!(-1, {
        let Some(json) = cstr_lossy(desc_json) else {
            sink_str(err_sink, err_ctx, "null descriptor");
            return -1;
        };
        let desc: tmux_plugin_abi::LoadDescriptor =
            match serde_json::from_str(&json) {
                Ok(d) => d,
                Err(e) => {
                    sink_str(err_sink, err_ctx, &format!("bad descriptor: {e}"));
                    return -1;
                }
            };
        match reload::upsert(desc) {
            Ok(outcome) => {
                sink_str(err_sink, err_ctx, outcome);
                0
            }
            Err(e) => {
                sink_str(err_sink, err_ctx, &e);
                -1
            }
        }
    })
}

/// Reload a plugin from disk (or all plugins when `name` is NULL): every
/// instance is swapped transactionally with snapshot/migrate and a new
/// generation; failures keep the old instance running. Errors go to the
/// sink; returns -1 if any plugin failed.
///
/// # Safety
/// `name` NUL-terminated or NULL; `err_sink` valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_reload(
    name: *const c_char,
    err_sink: pgh_sink,
    err_ctx: *mut c_void,
) -> c_int {
    ffi_guard!(-1, {
        let names: Vec<String> = match cstr_lossy(name) {
            Some(n) => vec![n],
            None => REGISTRY
                .with(|r| r.borrow().plugins.keys().cloned().collect()),
        };
        let mut rc = 0;
        for n in names {
            if let Err(e) = reload::reload(&n) {
                sink_str(err_sink, err_ctx, &format!("{n}: {e}\n"));
                rc = -1;
            }
        }
        rc
    })
}

/// Enable (1) or disable (0) a plugin. Returns 0, or -1 if unknown.
///
/// # Safety
/// `name` must be NUL-terminated.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_set_enabled(
    name: *const c_char,
    enabled: c_int,
) -> c_int {
    ffi_guard!(-1, {
        let Some(name) = cstr_lossy(name) else { return -1 };
        match reload::set_enabled(&name, enabled != 0) {
            Ok(()) => 0,
            Err(_) => -1,
        }
    })
}

/// Write the tail of the plugin log ring (optionally filtered by plugin
/// name; NULL = all) into the sink as preformatted lines.
///
/// # Safety
/// `name` NUL-terminated or NULL; `sink` valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_query_log(
    name: *const c_char,
    limit: u32,
    sink: pgh_sink,
    ctx: *mut c_void,
) {
    ffi_guard!((), {
        let name = cstr_lossy(name);
        let text = hostlog::query(name.as_deref(), limit as usize);
        sink_str(sink, ctx, &text);
    })
}

/// Unload a plugin by name. Returns 0, or -1 if unknown. Guest on_unload
/// runs at the next drain.
///
/// # Safety
/// `name` must be NUL-terminated.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_unload(name: *const c_char) -> c_int {
    ffi_guard!(-1, {
        let Some(name) = cstr_lossy(name) else { return -1 };
        let found = REGISTRY.with(|r| r.borrow_mut().unload(&name));
        if found {
            0
        } else {
            -1
        }
    })
}

/// Feed one event (JSON, see ABI.md) into the plugin event queue.
///
/// ENQUEUE ONLY: never runs plugin code, so it is legal to call from
/// anywhere on the main thread, including from inside a vtable callback
/// (the one permitted re-entry). Guest delivery happens at the next
/// pgh_drain. The C side should call plugin_schedule_drain() afterwards.
///
/// # Safety
/// `event_json` must be a NUL-terminated string.
#[no_mangle]
pub unsafe extern "C" fn pgh_notify(event_json: *const c_char) {
    ffi_guard!((), {
        let Some(json) = cstr_lossy(event_json) else { return };
        events::enqueue_raw(json);
    })
}

/// Invalidate plugin state tied to a dead tmux object (kind = PGH_OBJ_*).
///
/// MARK AND QUEUE ONLY: never runs guest code, because this is called from
/// deep teardown paths (window_destroy can run inside command-queue
/// callbacks). Instance unload work happens at the next pgh_drain.
#[no_mangle]
pub extern "C" fn pgh_object_destroyed(kind: c_int, id: u32) {
    ffi_guard!((), {
        let scope = match kind {
            ffi::PGH_OBJ_SESSION => ScopeId::Session(id),
            ffi::PGH_OBJ_WINDOW => ScopeId::Window(id),
            ffi::PGH_OBJ_PANE => ScopeId::Pane(id),
            ffi::PGH_OBJ_CLIENT => return, // no client-scoped instances
            _ => return,
        };
        events::object_destroyed(scope);
    })
}

/// Deliver the result of an async operation started through the vtable
/// (run_job, run_command, timer_start, ...).
///
/// ENQUEUE ONLY, like pgh_notify: legal to call from any main-thread
/// context, including from inside vtable callbacks. Generation checks at
/// drain time drop completions whose instance died or was reloaded. The C
/// side should call plugin_schedule_drain() afterwards.
///
/// # Safety
/// `result_json` must be NUL-terminated.
#[no_mangle]
pub unsafe extern "C" fn pgh_async_complete(
    token: u64,
    result_json: *const c_char,
    is_error: c_int,
) {
    ffi_guard!((), {
        let json = cstr_lossy(result_json).unwrap_or_else(|| "{}".into());
        EVENTS.with(|e| {
            e.borrow_mut().deliveries.push_back(
                state::Delivery::AsyncComplete { token, json, is_error: is_error != 0 },
            );
        });
    })
}

/// Run queued plugin work for at most `max_us` microseconds of wall clock
/// (0 = default budget). Returns the number of deliveries still queued;
/// when nonzero the C side re-schedules via its zero-timeout evtimer so the
/// libevent loop breathes between slices.
///
/// ONLY to be called from the command-queue drain callback (the safe point).
#[no_mangle]
pub extern "C" fn pgh_drain(max_us: u32) -> u32 {
    ffi_guard!(0, events::drain(max_us))
}

/// Write a human-readable plugin listing (for `show-plugins`) into the sink.
/// Preformatted text, one line per plugin (plus per-instance lines when
/// `verbose` is nonzero); the C side prints lines verbatim.
///
/// # Safety
/// `sink` must be a valid callback; `ctx` is passed through untouched.
#[no_mangle]
pub unsafe extern "C" fn pgh_query_plugins(verbose: c_int, sink: pgh_sink, ctx: *mut c_void) {
    ffi_guard!((), {
        let text = REGISTRY.with(|r| r.borrow().query_text(verbose != 0));
        sink_str(sink, ctx, &text);
    })
}
