//! tmux plugin host.
//!
//! Linked into the tmux server as a staticlib. Embeds Wasmtime and manages
//! plugin instances; tmux talks to it through the `pgh_*` exports declared in
//! include/plugin-host.h (generated by cbindgen; regenerate with
//! `cbindgen --crate plugin-host --output ../include/plugin-host.h` from the
//! host/ directory whenever the FFI surface changes).

mod abi;
mod caps;
mod dispatch;
mod engine;
mod events;
mod ffi;
mod fsbox;
mod fsworker;
mod hostlog;
mod intern;
mod manifest;
mod modes;
mod registry;
mod reload;
mod sqlite;
mod state;
mod tokens;
mod worker;

pub use ffi::*;

use std::ffi::{c_void, CStr};
use std::os::raw::{c_char, c_int};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::OnceLock;

use registry::ScopeId;
use state::{EVENTS, REGISTRY};

static VTABLE: OnceLock<pgh_host_vtable> = OnceLock::new();

/// Set when the host crate itself has failed (an unattributable panic).
/// All pgh_* entry points become no-ops; this must never kill tmux.
static POISONED: AtomicBool = AtomicBool::new(false);

pub(crate) fn vtable() -> Option<&'static pgh_host_vtable> {
    VTABLE.get()
}

pub(crate) fn poison() {
    POISONED.store(true, Ordering::Relaxed);
    hostlog::error("host", "plugin host poisoned by internal error; plugins are disabled");
}

pub(crate) fn poisoned() -> bool {
    POISONED.load(Ordering::Relaxed)
}

/// Wrap every FFI export: catch unwinds so a host bug can never unwind into
/// C and never kills the user's tmux server.
macro_rules! ffi_guard {
    ($default:expr, $body:expr) => {{
        if crate::poisoned() {
            return $default;
        }
        match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| $body)) {
            Ok(v) => v,
            Err(_) => {
                crate::poison();
                $default
            }
        }
    }};
}
#[allow(unused_imports)] // used by other modules as they come online
pub(crate) use ffi_guard;

/// Copy a NUL-terminated C string into an owned String (lossy for any
/// non-UTF-8 bytes, which tmux names can technically contain).
pub(crate) unsafe fn cstr_lossy(ptr: *const c_char) -> Option<String> {
    if ptr.is_null() {
        return None;
    }
    Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
}

/// Push a &str through a pgh_sink.
pub(crate) unsafe fn sink_str(sink: pgh_sink, ctx: *mut c_void, s: &str) {
    sink(ctx, s.as_ptr() as *const c_char, s.len());
}

/// Initialize the plugin host. Must be called once, from the tmux server
/// main thread, before any other pgh_* function. Returns 0 on success.
///
/// # Safety
/// `vt` must point to a fully-populated vtable; the function pointers must
/// stay valid for the life of the process.
#[no_mangle]
pub unsafe extern "C" fn pgh_init(vt: *const pgh_host_vtable) -> c_int {
    ffi_guard!(-1, {
        if vt.is_null() {
            return -1;
        }
        if VTABLE.set(*vt).is_err() {
            return -1; // double init
        }
        hostlog::debug("host", "plugin host initialized");
        0
    })
}

/// Shut down the plugin host: unload all plugins and stop the epoch ticker
/// thread. Called once from the server exit path; pgh_* calls after this are
/// no-ops. Safe to call even if pgh_init failed.
#[no_mangle]
pub extern "C" fn pgh_shutdown() {
    ffi_guard!((), {
        // Finish (and join) the worker pool first: its in-flight fs jobs
        // read and write pinned guest memory, so the stores must still be
        // alive here.
        worker::shutdown();
        // The pool is joined, so no job can still hold a root or run a
        // statement; drop the cached sandbox descriptors and close the
        // database connections (the last close checkpoints each WAL).
        fsbox::forget_all();
        sqlite::forget_all();
        // Give every live instance its on_unload (tiny budget) before the
        // stores drop: server shutdown is a safe point like any drain.
        let mut doomed: Vec<registry::Instance> = Vec::new();
        REGISTRY.with(|r| {
            let mut reg = r.borrow_mut();
            doomed.append(&mut reg.dying);
            let keys: Vec<usize> =
                reg.instances.iter().map(|(k, _)| k).collect();
            for key in keys {
                if let Some(inst) = reg.instances.remove(key) {
                    doomed.push(inst);
                }
            }
            reg.by_scope.clear();
        });
        for mut inst in doomed {
            let _ = inst.guest.call_on_unload();
        }
        REGISTRY.with(|r| {
            let mut reg = r.borrow_mut();
            // Stores are gone; dropping the EngineState joins the ticker.
            reg.plugins.clear();
            reg.modules.clear();
            reg.engine.take();
        });
        EVENTS.with(|e| e.borrow_mut().deliveries.clear());
        hostlog::debug("host", "plugin host shut down");
    })
}

/// Load (or replace) a plugin. `scope` may be NULL (defaults to server);
/// `caps` is an array of `ncaps` capability names; `opts` is an array of
/// `nopts` config entries ("key=value", or a bare "key" meaning true).
/// Compiles and validates the module synchronously (obvious errors are
/// written to `err_sink` and -1 returned); instantiation and guest init are
/// queued for the next drain. The C side should call
/// plugin_schedule_drain() after a successful return.
///
/// # Safety
/// All strings must be NUL-terminated; the arrays must hold the declared
/// counts; `err_sink` must be valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_load(
    name: *const c_char,
    path: *const c_char,
    scope: *const c_char,
    caps: *const *const c_char,
    ncaps: usize,
    opts: *const *const c_char,
    nopts: usize,
    err_sink: pgh_sink,
    err_ctx: *mut c_void,
) -> c_int {
    ffi_guard!(-1, {
        let (Some(name), Some(path)) = (cstr_lossy(name), cstr_lossy(path))
        else {
            sink_str(err_sink, err_ctx, "null name or path");
            return -1;
        };
        let scope = match cstr_lossy(scope).as_deref() {
            None | Some("server") => tmux_plugin_abi::ScopeType::Server,
            Some("session") => tmux_plugin_abi::ScopeType::Session,
            Some("window") => tmux_plugin_abi::ScopeType::Window,
            Some("pane") => tmux_plugin_abi::ScopeType::Pane,
            Some(other) => {
                sink_str(err_sink, err_ctx, &format!("bad scope {other:?}"));
                return -1;
            }
        };
        let read_array = |arr: *const *const c_char, n: usize| -> Vec<String> {
            if arr.is_null() {
                return Vec::new();
            }
            (0..n)
                .filter_map(|i| cstr_lossy(*arr.add(i)))
                .collect()
        };
        let caps = read_array(caps, ncaps);
        let mut config = serde_json::Map::new();
        for opt in read_array(opts, nopts) {
            match opt.split_once('=') {
                Some((k, v)) => {
                    config.insert(k.to_string(), v.into());
                }
                None => {
                    config.insert(opt, true.into());
                }
            }
        }
        let desc = tmux_plugin_abi::LoadDescriptor {
            name: name.clone(),
            path,
            scope,
            config: serde_json::Value::Object(config),
            caps,
        };
        match reload::upsert(desc) {
            Ok(outcome) => {
                // An explicit load-plugin takes the definition out of the
                // manifest pool: it is hand-managed until a sync re-adopts
                // it by name.
                REGISTRY.with(|r| {
                    if let Some(def) = r.borrow_mut().plugins.get_mut(&name) {
                        def.managed = false;
                    }
                });
                sink_str(err_sink, err_ctx, outcome);
                0
            }
            Err(e) => {
                sink_str(err_sink, err_ctx, &e);
                -1
            }
        }
    })
}

/// Reconcile the managed plugin pool against the TOML manifest at
/// `manifest_path` (see WRITING-PLUGINS.md): load new entries, upsert
/// changed ones, unload managed plugins the manifest no longer names. A
/// manifest that fails to parse or validate changes nothing and returns
/// -1 with the error in the sink; on success the sink receives a summary
/// line (plus any per-entry apply failures) and 0 is returned. The C side
/// should call plugin_schedule_drain() afterwards.
///
/// # Safety
/// `manifest_path` must be NUL-terminated; `err_sink` must be valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_sync(
    manifest_path: *const c_char,
    err_sink: pgh_sink,
    err_ctx: *mut c_void,
) -> c_int {
    ffi_guard!(-1, {
        let Some(path) = cstr_lossy(manifest_path) else {
            sink_str(err_sink, err_ctx, "null manifest path");
            return -1;
        };
        match manifest::sync_manifest(&path) {
            Ok(report) => {
                sink_str(err_sink, err_ctx, &report);
                0
            }
            Err(e) => {
                sink_str(err_sink, err_ctx, &e);
                -1
            }
        }
    })
}

/// Reload a plugin from disk (or all plugins when `name` is NULL): every
/// instance is swapped transactionally with snapshot/migrate and a new
/// generation; failures keep the old instance running. Errors go to the
/// sink; returns -1 if any plugin failed.
///
/// # Safety
/// `name` NUL-terminated or NULL; `err_sink` valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_reload(
    name: *const c_char,
    err_sink: pgh_sink,
    err_ctx: *mut c_void,
) -> c_int {
    ffi_guard!(-1, {
        let names: Vec<String> = match cstr_lossy(name) {
            Some(n) => vec![n],
            None => REGISTRY
                .with(|r| r.borrow().plugins.keys().cloned().collect()),
        };
        let mut rc = 0;
        for n in names {
            if let Err(e) = reload::reload(&n) {
                sink_str(err_sink, err_ctx, &format!("{n}: {e}\n"));
                rc = -1;
            }
        }
        rc
    })
}

/// Enable (1) or disable (0) a plugin. Returns 0, or -1 if unknown.
///
/// # Safety
/// `name` must be NUL-terminated.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_set_enabled(
    name: *const c_char,
    enabled: c_int,
) -> c_int {
    ffi_guard!(-1, {
        let Some(name) = cstr_lossy(name) else { return -1 };
        match reload::set_enabled(&name, enabled != 0) {
            Ok(()) => 0,
            Err(_) => -1,
        }
    })
}

/// Write the tail of the plugin log ring (optionally filtered by plugin
/// name; NULL = all) into the sink as preformatted lines.
///
/// # Safety
/// `name` NUL-terminated or NULL; `sink` valid.
#[no_mangle]
pub unsafe extern "C" fn pgh_query_log(
    name: *const c_char,
    limit: u32,
    sink: pgh_sink,
    ctx: *mut c_void,
) {
    ffi_guard!((), {
        let name = cstr_lossy(name);
        let text = hostlog::query(name.as_deref(), limit as usize);
        sink_str(sink, ctx, &text);
    })
}

/// Unload a plugin by name. Returns 0, or -1 if unknown. Guest on_unload
/// runs at the next drain.
///
/// # Safety
/// `name` must be NUL-terminated.
#[no_mangle]
pub unsafe extern "C" fn pgh_plugin_unload(name: *const c_char) -> c_int {
    ffi_guard!(-1, {
        let Some(name) = cstr_lossy(name) else { return -1 };
        let found = REGISTRY.with(|r| r.borrow_mut().unload(&name));
        if found {
            0
        } else {
            -1
        }
    })
}

/// Feed one binary event buffer (header + field block, see abi-types) into
/// the plugin event queue.
///
/// ENQUEUE ONLY: never runs plugin code, so it is legal to call from
/// anywhere on the main thread, including from inside a vtable callback
/// (the one permitted re-entry). Guest delivery happens at the next
/// pgh_drain. The C side should call plugin_schedule_drain() afterwards.
///
/// # Safety
/// `event` must point at `len` readable bytes (copied before returning).
#[no_mangle]
pub unsafe extern "C" fn pgh_notify(event: *const u8, len: usize) {
    ffi_guard!((), {
        if event.is_null() {
            return;
        }
        let bytes = std::slice::from_raw_parts(event, len).to_vec();
        events::enqueue_raw(bytes);
    })
}

/// Intern a name (event name or payload key), returning its stable id
/// (>= 1). The same table serves guests through the `intern` import, so
/// the ids the C bridge writes into event buffers are the ids guests
/// subscribe to and compare against.
///
/// # Safety
/// `name` must be NUL-terminated.
#[no_mangle]
pub unsafe extern "C" fn pgh_intern(name: *const c_char) -> u32 {
    ffi_guard!(0, {
        let Some(name) = cstr_lossy(name) else { return 0 };
        intern::intern(&name)
    })
}

/// Invalidate plugin state tied to a dead tmux object (kind = PGH_OBJ_*).
///
/// MARK AND QUEUE ONLY: never runs guest code, because this is called from
/// deep teardown paths (window_destroy can run inside command-queue
/// callbacks). Instance unload work happens at the next pgh_drain.
#[no_mangle]
pub extern "C" fn pgh_object_destroyed(kind: c_int, id: u32) {
    ffi_guard!((), {
        let scope = match kind {
            ffi::PGH_OBJ_SESSION => ScopeId::Session(id),
            ffi::PGH_OBJ_WINDOW => ScopeId::Window(id),
            ffi::PGH_OBJ_PANE => ScopeId::Pane(id),
            ffi::PGH_OBJ_CLIENT => return, // no client-scoped instances
            _ => return,
        };
        events::object_destroyed(scope);
    })
}

/// Deliver the result of an async operation started through the vtable
/// (run_job, run_command, timer_start, ...). `err` is 0 on success or an
/// ErrorCode number; `data`/`len` carry the per-method payload (job
/// output; the error message when err != 0) and may be NULL/0.
///
/// ENQUEUE ONLY, like pgh_notify: legal to call from any main-thread
/// context, including from inside vtable callbacks. Generation checks at
/// drain time drop completions whose instance died or was reloaded. The C
/// side should call plugin_schedule_drain() afterwards.
///
/// # Safety
/// `data` must point at `len` readable bytes or be NULL (copied before
/// returning).
#[no_mangle]
pub unsafe extern "C" fn pgh_async_complete(
    token: u64,
    err: c_int,
    v0: i64,
    v1: i64,
    data: *const u8,
    len: usize,
) {
    ffi_guard!((), {
        let data = if data.is_null() || len == 0 {
            Vec::new()
        } else {
            std::slice::from_raw_parts(data, len).to_vec()
        };
        EVENTS.with(|e| {
            e.borrow_mut().deliveries.push_back(
                state::Delivery::AsyncComplete { token, err, v0, v1, data },
            );
        });
    })
}

/// Deliver a mode event (mode-key, mode-resize, mode-closed) for a plugin
/// UI mode opened through the mode_open vtable call. `event` is a complete
/// binary event buffer built by the C side (including the mode field).
///
/// ENQUEUE ONLY, like pgh_notify: legal to call from any main-thread
/// context, including from inside vtable callbacks. Ownership and
/// generation checks at drain time drop events whose owning instance died
/// or was reloaded. The C side should call plugin_schedule_drain()
/// afterwards.
///
/// # Safety
/// `event` must point at `len` readable bytes (copied before returning).
#[no_mangle]
pub unsafe extern "C" fn pgh_mode_event(
    mode_id: u64,
    event: *const u8,
    len: usize,
) {
    ffi_guard!((), {
        if event.is_null() {
            return;
        }
        let bytes = std::slice::from_raw_parts(event, len).to_vec();
        EVENTS.with(|e| {
            e.borrow_mut().deliveries.push_back(
                state::Delivery::ModeEvent { mode_id, bytes },
            );
        });
    })
}

/// Run queued plugin work for at most `max_us` microseconds of wall clock
/// (0 = default budget). Returns the number of deliveries still queued;
/// when nonzero the C side re-schedules via its zero-timeout evtimer so the
/// libevent loop breathes between slices.
///
/// ONLY to be called from the command-queue drain callback (the safe point).
#[no_mangle]
pub extern "C" fn pgh_drain(max_us: u32) -> u32 {
    ffi_guard!(0, events::drain(max_us))
}

/// The worker pool's pollable doorbell fd (created on first call). The
/// C side registers a persistent read event on it whose callback calls
/// pgh_fs_drain() then plugin_schedule_drain(). Returns -1 on failure.
/// The name predates the pool: it carries db completions too.
#[no_mangle]
pub extern "C" fn pgh_fs_notify_fd() -> c_int {
    ffi_guard!(-1, worker::notify_fd())
}

/// Move finished worker completions (fs and db) onto the plugin delivery
/// queue (they are delivered to guests at the next pgh_drain). Main
/// thread only; called from the doorbell event callback.
#[no_mangle]
pub extern "C" fn pgh_fs_drain() {
    ffi_guard!((), worker::drain())
}

/// Write a human-readable plugin listing (for `show-plugins`) into the sink.
/// Preformatted text, one line per plugin (plus per-instance lines when
/// `verbose` is nonzero); the C side prints lines verbatim.
///
/// # Safety
/// `sink` must be a valid callback; `ctx` is passed through untouched.
#[no_mangle]
pub unsafe extern "C" fn pgh_query_plugins(verbose: c_int, sink: pgh_sink, ctx: *mut c_void) {
    ffi_guard!((), {
        let text = REGISTRY.with(|r| r.borrow().query_text(verbose != 0));
        sink_str(sink, ctx, &text);
    })
}
