#!/bin/sh
# Turn skills/<name>/SKILL.md into skills-data.c: one row per skill with
# its name (the directory), the harness stub name and description (from
# the frontmatter) and the body after the frontmatter, as a byte array so
# no compiler limit on string literals applies.
#
#   sh skills/mkskills.sh skills/*/SKILL.md > skills-data.c
set -e

# Escape a short string for a C literal.
cstr() {
	printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/??/?\\?/g'
}

# A frontmatter field: the file starts with ---, the field sits before the
# closing ---.
field() {
	awk -v key="$2" '
		NR == 1 && $0 != "---" { exit }
		/^---$/ { n++; if (n == 2) exit; next }
		n == 1 && index($0, key ":") == 1 {
			sub("^" key ":[ \t]*", ""); print; exit
		}' "$1"
}

# The body: everything after the frontmatter (or the whole file without one).
body() {
	awk '
		NR == 1 && $0 != "---" { body = 1 }
		!body && /^---$/ { n++; if (n == 2) body = 1; next }
		body { print }' "$1"
}

echo '/* GENERATED by skills/mkskills.sh from skills/<name>/SKILL.md; do not edit. */'
echo '#include "tmux.h"'
echo
i=0
for f in "$@"; do
	name=$(basename "$(dirname "$f")")
	printf 'static const char skill_text_%d[] = {\n' "$i"
	body "$f" | od -An -v -tu1 | tr -s ' \n' ' ' | fold -w 78 -s |
	    sed -e 's/^ *//' -e 's/ *$//' -e 's/ /,/g' -e 's/$/,/' -e 's/^/	/'
	printf '	0 };\n\n'
	i=$((i + 1))
done
echo 'const struct skill skills[] = {'
i=0
for f in "$@"; do
	name=$(basename "$(dirname "$f")")
	stub=$(field "$f" name)
	[ -n "$stub" ] || stub="tmux2-$name"
	desc=$(field "$f" description)
	printf '\t{ "%s", "%s",\n' "$(cstr "$name")" "$(cstr "$stub")"
	printf '\t  "%s",\n' "$(cstr "$desc")"
	printf '\t  skill_text_%d },\n' "$i"
	i=$((i + 1))
done
echo '	{ NULL, NULL, NULL, NULL }'
echo '};'
